name: Simple E2E Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests and generate report
      - name: Run tests
        run: |
          echo "Running tests..."
          # Simulate test output for demonstration
          mkdir -p reports
          echo "<html><body><h1>Test Report</h1></body></html>" > reports/test-report.html

      # Step 5: Upload test report as artifact
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-report
          path: reports/test-report.html

      # Step 6: Add PR comment with test results
      - name: Add PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const commentBody = `
            ### E2E Test Report Summary
            - **Tests Run**: 10
            - **Passed**: 10
            - **Failed**: 0
            - **Skipped**: 0
            - [View Test Report](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}/artifacts)
            `;
            
            console.log('Adding comment to PR:', context.issue.number);
            
            // Add comment to the pull request
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody,
            });
