name: Frontend Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate E2E Test HTML report
        run: |
          npm test
          mkdir -p reports
          ls -lah reports

      - name: Upload E2E Test HTML test report
        if: always()
        uses: actions/upload-artifact@v4.0.0
        with:
          name: unittest-html-test-report
          path: reports/test-report.html

      - name: Deploy E2E Test report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: e2e-gh-pages

      - name: Analyzing E2ETest Results
        id: e2e_extract_summary
        run: |
          TEST_SUMMARY="Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 720.144 sec - in TestSuite"
          TOTAL_TESTS=$(echo "$TEST_SUMMARY" | grep -oP '(?<=Tests run: )\d+')
          FAILED_TESTS=$(echo "$TEST_SUMMARY" | grep -oP '(?<=Failures: )\d+')
          SKIPPED_TESTS=$(echo "$TEST_SUMMARY" | grep -oP '(?<=Skipped: )\d+')
          PASSED_TESTS=$((TOTAL_TESTS - FAILED_TESTS - SKIPPED_TESTS))
          if [ "$FAILED_TESTS" -gt 0 ]; then
            E2E_RESULT="FAILED"
          else
            E2E_RESULT="SUCCESS"
          fi
          echo "TEST_SUMMARY=$TEST_SUMMARY" >> $GITHUB_ENV
          echo "TOTAL_TESTS=$TOTAL_TESTS" >> $GITHUB_ENV
          echo "FAILED_TESTS=$FAILED_TESTS" >> $GITHUB_ENV
          echo "SKIPPED_TESTS=$SKIPPED_TESTS" >> $GITHUB_ENV
          echo "PASSED_TESTS=$PASSED_TESTS" >> $GITHUB_ENV
          echo "E2E_RESULT=$E2E_RESULT" >> $GITHUB_ENV

      - name: Add E2E Test PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const artifactUrl = `${{ steps.artifact.outputs.artifact-url }}`;
            const commentBody = `
            ### E2E Test Report Summary
            - **E2E Test Result**: ${process.env.E2E_RESULT || 'Unknown'}
            - **Total Tests**: ${process.env.TOTAL_TESTS || '0'}
            - **Passed Tests**: ${process.env.PASSED_TESTS || '0'}
            - **Failed Tests**: ${process.env.FAILED_TESTS || '0'}
            - **Skipped Tests**: ${process.env.SKIPPED_TESTS || '0'}
            - **[Download E2E Test Report](${artifactUrl})**
            `;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
