name: Frontend Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate HTML report
        run: ｜
          npm test && ls -lah
          cat reports/test-report.html


      - name: Upload HTML test report
        if: always()
        uses: actions/upload-artifact@v4.0.0
        with:
          name: unittest-html-test-report
          path: reports/test-report.html

      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: 'reports/test-report.html'
          job_summary: true

      - name: Deploy report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./reports

  Java-Test:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      # 2. 设置 JDK 环境
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'         # 指定 Java 版本
          distribution: 'zulu'  
          # 可以选择其他发行版，如 'zulu'

      - name: 查看当前目录信息
        run: |
          pwd
          ls
          ls -lah
          echo "查看maven版本：" && mvn -version
          echo "查看Java版本：" && java -version
